version: "3.6"

services:
    backend:
        container_name: students-admin-server
        build: ./
        command: npm start

        environment: 
            NODE_ENV: development
            PORT: 3210
            MONGO_HOST: mongodb://mongo:27018/students-admin

        working_dir: /usr/src/students-admin
        ports: 
            - "3210:3210"
        volumes: 
            - ./:/usr/src/students-admin
            - /usr/src/students-admin/node_modules

    database:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"
        volumes: 
            - ./:/usr/src/students-admin
