version: "3.6"

services:
    backend:
        container_name: students-admin-server
        build: ./
        command: npm start

        env_file:
            - .env
        environment: 
            NODE_ENV: development
            PORT: 3000
            MONGO_HOST: ${MONGO_HOST:-mongodb://mongo:27017/students-admin}

        working_dir: /usr/src/students-admin
        ports: 
            - "3000:3000"
        volumes: 
            - $PWD/server/uploads:/usr/src/students-admin/uploads

    database:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"
        volumes: 
            - $PWD/dbdata:/data/db
